Update workflow_test.yml

diff --git a/.github/workflows/workflow_test.yml b/.github/workflows/workflow_test.yml
--- a/.github/workflows/workflow_test.yml
+++ b/.github/workflows/workflow_test.yml
@@ -12,8 +12,11 @@ jobs:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
     outputs:
-      cluster_name: ${{ steps.output.outputs.cluster_name }}
-      cluster_endpoint: ${{ steps.output.outputs.cluster_endpoint }}
+      #cluster_name: ${{ steps.output.outputs.cluster_name }}
+      #cluster_endpoint: ${{ steps.output.outputs.cluster_endpoint }}
+      
+      cluster_name: ${{ steps.tf_outputs.outputs.cluster_name }}
+      cluster_endpoint: ${{ steps.tf_outputs.outputs.cluster_endpoint }}
 
     steps:
       - name: Checkout repository
@@ -42,22 +45,23 @@ jobs:
         working-directory: ./terraform
         shell: bash
         run: |
-            TF_BIN=${TERRAFORM_CLI_PATH:-terraform}
-          
-            cluster_name=$($TF_BIN output -raw cluster_name 2>/dev/null || echo "")
-            cluster_endpoint=$($TF_BIN output -raw cluster_endpoint 2>/dev/null || echo "")
-          
-            echo "Terraform Outputs:"
-            echo " - cluster_name: ${cluster_name:-<empty>}"
-            echo " - cluster_endpoint: ${cluster_endpoint:-<empty>}"
-          
-            if [[ -z "$cluster_name" ]]; then
-              echo "❌ Missing cluster_name output!"
-              exit 1
-            fi
-            
-            echo "cluster_name=${cluster_name}" >> $GITHUB_OUTPUT
-            echo "cluster_endpoint=${cluster_endpoint}" >> $GITHUB_OUTPUT
+          set -e
+          TF_BIN=${TERRAFORM_CLI_PATH:-terraform}
+
+          cluster_name=$($TF_BIN output -raw cluster_name 2>/dev/null || echo "")
+          cluster_endpoint=$($TF_BIN output -raw cluster_endpoint 2>/dev/null || echo "")
+
+          echo "Terraform Outputs:"
+          echo " - cluster_name: ${cluster_name:-<empty>}"
+          echo " - cluster_endpoint: ${cluster_endpoint:-<empty>}"
+
+          if [[ -z "$cluster_name" ]]; then
+            echo "❌ Missing cluster_name output!"
+            exit 1
+          fi
+
+          echo "cluster_name=${cluster_name}" >> $GITHUB_OUTPUT
+          echo "cluster_endpoint=${cluster_endpoint}" >> $GITHUB_OUTPUT
           
           #echo "Fetching Terraform outputs safely..."
           #cluster_name=$(terraform output -raw cluster_name 2>/dev/null || echo "unknown")
